name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pytest flake8 PyGithub requests huggingface_hub|| true
          pip install fastapi boto3 sqlalchemy python-multipart

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.PHASE2_TOKEN }}
        run: |
          echo "Running tests..."
          export PYTHONPATH=$PYTHONPATH:$(pwd)/phase1
          pytest phase1/tests || true

          export PYTHONPATH=$PYTHONPATH:$(pwd)/phase2
          pytest tests || true

      - name: Lint
        run: |
          echo "Running flake8..."
          export PYTHONPATH=$PYTHONPATH:$(pwd)/phase1
          flake8 phase1/src phase1/tests || true

          export PYTHONPATH=$PYTHONPATH:$(pwd)/phase2
          flake8 phase2/src tests || true

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Debug OIDC token
        run: |
          echo "Debugging OIDC token..."
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
               "$ACTIONS_ID_TOKEN_REQUEST_URL"

      - name: Run deploy script
        run: bash deploy/deploy.sh

